name: sharppy
channels:
  - conda-forge
  - conda-forge/label/testing
  - anaconda
dependencies:
  - python=3
  - numpy>=1.15
  - pyside2>=5.12
  - sphinx
  - pytest
  - qtpy
  - sphinx_rtd_theme
  - xarray
  - h5netcdf
  - requests
  - python-dateutil
  - pyinstaller
  - pandas
  - cartopy
  - setuptools
  - matplotlib
  - certifi
  - pip
  - pip:
    - sphinx-prompt
    - pydocstyle